name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive application files
      run: zip -r myapp.zip .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YOUR_APP_SERVICE_NAME'  # Replace with your Azure App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Set this secret in your repository

    - name: Restart Azure Web App Service
      run: |
        az webapp restart --name YOUR_APP_SERVICE_NAME --resource-group YOUR_RESOURCE_GROUP_NAME

    - name: Start Gunicorn
      run: |
        gunicorn --workers=3 app:app  # Adjust this based on your app configuration
